### ISSUE TITLE
error in lfqcd: in `join': no implicit conversion of nil into String

### ISSUE THREAD

**Issue by droe-nmdp** [mariusmni/lfqc#2]
I'm getting this error on a 85M fastq.lfqc file. Any suggestions?

> ruby $HOME/bin/lfqc/lfqc/lfqcd.rb test.lfqc 
> Work dir /project/compbioRAID1/davidr/data/fastq/test/tmp_8258cd893b4d50d1484e297413953891_test.lfqc
> Running tar xf /project/compbioRAID1/davidr/data/fastq/test/test.lfqc -C /project/compbioRAID1/davidr/data/fastq/test/tmp_8258cd893b4d50d1484e297413953891_test.lfqc
> /home/grad02/davidr/bin/lfqc/lfqc/lfqcd.rb:29:in `join': no implicit conversion of nil into String (TypeError)
>     from /home/grad02/davidr/bin/lfqc/lfqc/lfqcd.rb:29:in`decompress'
>     from /home/grad02/davidr/bin/lfqc/lfqc/lfqcd.rb:207:in `block in maind'
>     from /usr/lib/ruby/2.3.0/benchmark.rb:293:in`measure'
>     from /home/grad02/davidr/bin/lfqc/lfqc/lfqcd.rb:206:in `maind'
>     from /home/grad02/davidr/bin/lfqc/lfqc/lfqcd.rb:214:in`<main>'

**Comment by mariusmni** [comment]
https://github.com/mariusmni/lfqc#compiling-zpaq-and-lpaq-if-errors-occur

**Comment by droe-nmdp** [comment]
Thank you. I initially thought that was just for compilation errors. Sorry I missed it.
