### ISSUE TITLE
input from stdin

### ISSUE THREAD

**Issue by droe-nmdp** [mariusmni/lfqc#3]
Thank you for your software. 

Can you help me figure out how to use input from stdin? For example, I would like to extact fastq from a bam and directly input to lfqc, maybe like this:

  ruby lfqc.rb <(samtools view -uf128 file.bam | samtools bam2fq -nO -)

**Comment by mariusmni** [comment]
Try named pipe

mkfifo data
YourCommand > data & ruby lfqc.d data

http://m.linuxjournal.com/article/2156

**Comment by droe-nmdp** [comment]
Thank you!
