### ISSUE TITLE
can run on smaller, but not larger, files

### ISSUE THREAD

**Issue by droe-nmdp** [mariusmni/lfqc#4]
I can sucessfully compress/decompress relatively small files, but not relatively large ones. I can always create the .lfqc file, but decompressing fails with:
    lfqcd.rb:28:in `join': can't convert nil into String (TypeError)

I can sucessfully compress/decompress a fastq file that has 40 million lines (~3G). This is a subset of a larger file. From this, I conclude my execubles are build correctly.

But larger subsets (e.g., 100 million lines, 7.7G) fail. I tried on muliple files, so I'm fairly confident is isn't something about the file.

I'm running on Ubuntu 14.04.5 with 20G of memory.

Below is part of the output. Notice the ' input file too big' message from lpaq8. I'm not sure this is important, but it doesn't appear in the successfull, smaller test case.

```
...
Adding 3775.000000 MB in 1 files -method 56 -threads 11 at 2016-10-06 15:50:44.
input file too big
Data compression time   0.270000   0.100000   0.870000 (  0.562931)
... 
Running tar cf test.fastq.lfqc test.fastq_name_sep.zpaq test.fastq_data_noEOL.lpaq test.fastq_qual.zpaq
tar: test.fastq_data_noEOL.lpaq: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Clean up...
Done.
```

Any suggestions?

**Comment by mariusmni** [comment]
lpaq8 seems to have a limitation - 31 bits to store lengths, so no more than 2GB

Try to use zpaq for both data and quality compression. Go to this line:

https://github.com/mariusmni/lfqc/blob/master/lfqc/lfqc.rb#L15

And replace 'lpaq' with 'zpaq'

**Comment by droe-nmdp** [comment]
That worked! Thank you.
